// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<string, any> = {
  default: {
    "focus-tabs": {
      name: "focus-tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/default/annui/focus-tabs.tsx",
          type: "registry:ui",
          target: "",
        },
        {
          path: "registry/default/lib/context.ts",
          type: "registry:lib",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/registry/default/annui/focus-tabs.tsx"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    "focus-tabs-demo": {
      name: "focus-tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["focus-tabs"],
      files: [
        {
          path: "registry/default/example/focus-tabs-demo.tsx",
          type: "registry:example",
          target: "",
        },
      ],
      component: React.lazy(
        () => import("@/registry/default/example/focus-tabs-demo.tsx"),
      ),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    utils: {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/default/lib/utils.ts",
          type: "registry:lib",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
    context: {
      name: "context",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [
        {
          path: "registry/default/lib/context.ts",
          type: "registry:lib",
          target: "",
        },
      ],
      component: React.lazy(() => import("@/registry/default/lib/context.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: [],
    },
  },
};
